### ISSUE TITLE
Login issues on hub.grid.tf

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/threefold_connect#436]
No data shown on app. Selecting the correct icon but nothing happens so no login. Blocking our devs

**Comment by sabrinasadik** [comment]
![photo_2022-04-13 11 13 03](https://user-images.githubusercontent.com/31733464/163142684-54ca2643-7629-4b09-8f74-5a91a3454503.jpeg)

**Comment by sabrinasadik** [comment]
https://hub.grid.tf/

**Comment by LennertDefauw1** [comment]
Due the update to null safety support, null values are almost never accepted anymore. I assumed 3th party apps without asking any scope as required data would provide just an empty scope as JSON object, but tf-hub didn't add any scope as parameter, which returned into null in the app, since the new update of the app this broke the login attempt.

**Comment by LennertDefauw1** [comment]
Quick fix => added an empty scope object as parameter in tf-hub = DONE

On our side, we will fix the error and redeploy it to the app / playstore
