### ISSUE TITLE
Change wording in registration 

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/threefold_connect#441]
instead of 

Hi, please choose a ThreeFold Connect Id. 

Change into

Please choose a ThreeFold Connect username.

Also, is the .3bot in the ID still needed?

**Comment by ken-de-moor** [comment]
The .3bot thing is something that's still required for now because of backwards compatibility reasons. Some tools and databases already have it hardcoded in now and just removing it entirely now will break a lot of things.

However there are definitely options to hide it more for the user. The fact the backend needs it to work shouldn't be relevant for the user. Just need to be very sure every place that has the login doesn't tell people to "fill in their 3bot name". Or they'll get confused.
