### ISSUE TITLE
threefold connect account verification failed

### ISSUE THREAD

**Issue by Eslam-Nawara** [threefoldtech/threefold_connect#557]
### Description

when creating a new account using threefold connect mobile app and trying to verify the account it fails

### Steps to reproduce

- create new account on threefold connect
- open identity and click verify
- try to verify the account using the verification mail, it always fails

### Logs/Alerts
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/67752395/043f77f6-f6a7-4a2a-a3be-6e6ee427fd04)

**Comment by AhmedHanafy725** [comment]
@Eslam-Nawara  what is the app version? and is it Android or iOS and what is its version?

**Comment by Mahmoud-Emad** [comment]
@Eslam-Nawara,

I don't see any issues with verifying email addresses. I created three accounts and successfully verified each one. Please ensure you're using the correct link. When you click the verification button, it sends you an email with the verification link. Keep in mind that each time you press the verify button, it generates and sends a new link. The old link will expire, which is expected behavior.

**Comment by A-Harby** [comment]
Verified, changed my mail to re-try the verification and it also worked fine with me.
![image](https://github.com/threefoldtech/threefold_connect/assets/109473873/66ed88a6-c727-45c2-99ce-4984c354a4a0)
![image](https://github.com/threefoldtech/threefold_connect/assets/109473873/68d8b719-79cc-4386-a9de-eae50d833b4d)

This will happen if we pressed the verification button more than one, so all the links will not work except the last one
![image](https://github.com/threefoldtech/threefold_connect/assets/109473873/6468fa1b-4aca-421d-adb0-300fcf092a1f)
