### ISSUE TITLE
Can't create a farm

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/threefold_connect#603]
I tried creating a farm and followed the steps, Choose the wallet and typed a name and accepted the terms.

It kept loading like that for too long that I had to close the app.
![image](https://github.com/threefoldtech/threefold_connect/assets/109473873/6a3e2652-fa88-442a-8aae-b9ccba98d2da)

And secondly, if I create a farm, where should it be found? The wallet is created by the app and is not connected to any twin.

**Comment by khaledyoussef24** [comment]
the issue is no longer reproducabile created these farms without any issue it may take time only
version 3.9.1
![Image](https://github.com/user-attachments/assets/8b0c313f-daf5-471d-bcbe-8a2bb79113e8)
[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/206114?expand_section=407474#case_4050852)
